# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip


  platform :ios, min_ios_version_supported
  prepare_react_native_project!
  

  target 'Cauldron' do
  
    config = use_native_modules!
    pod 'Plaid'
  
    use_react_native!(
      :path => config[:reactNativePath],
      :app_path => "#{Pod::Config.instance.installation_root}/.."
    )
  
    target 'CauldronTests' do
      inherit! :complete
      # Pods for testing
    end
  
    post_install do |installer|
      react_native_post_install(
        installer,
        config[:reactNativePath],
        :mac_catalyst_enabled => false,
        #:ccache_enabled => true  # Uncomment for faster builds if using Ccache
      )
    end
  end
